name: 'aspyre2'

channels:
  - defaults

dependencies:
  - cython
  - fftw
  - pandas>=0.23.4
  - pip
  - pytest
  - python=3.6
  - scikit-image
  - scikit-learn
  - scipy=0.19.1
  - pip:
    - importlib_resources>=1.0.2
    - mrcfile
    - numpy==1.16.1
    - pyfftw
    - tqdm
    - finufftpy-1.1.1-cp36-cp36m-linux_ppc64le.whl

