name: 'aspyre'

channels:
  - defaults
  - conda-forge

dependencies:
  - cython=0.26.1
  - make
  - numpy=1.14.2
  - numpydoc=0.7.0
  - pandas>=0.23.4
  - pip
  - pybind11
  - pytest=3.2.1
  - python=3.6
  - scikit-image=0.14.0
  - scipy=0.19.1
  - sphinxcontrib-bibtex=0.4.0
  - wheel
  - pip:
    - coveralls
    - finufftpy
    - importlib_resources>=1.0.2
    - mrcfile
    - pytest-cov
    - sphinx-rtd-theme==0.4.2
    - tqdm
